# Generated by Django 3.2.13 on 2022-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getxml', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packeage',
            new_name='Package',
        ),
    ]
